### ISSUE TITLE
Can this be used by abot?

### ISSUE THREAD

**Issue by heri** [itsabot/plugin_restaurants#1]
I added `plugin_restaurants` in the `plugins.json` file but install won't work

```
can't load package: /Users/heri/Sites/go/src/github.com/itsabot/abot/plugins.go:8:2: import "github.com/itsabot/plugin_restaurants" is a program, not an importable package
```

Missing files? or restaurants.go needs to be updated? I saw at the top it's declared as `package main` instead of `package name_of_plugin` like weather, calendar and other plugins

**Comment by egtann** [comment]
Hi Heri. This is using an outdated API, so it needs to be updated to be more in line with weather and Twilio.  It's on our roadmap for v0.2 (ETA June 1, 2016): https://github.com/itsabot/abot/wiki/Roadmap

I'm also happy to accept pull requests to make this work with the latest version of Abot. If you're interested in contributing the necessary fixes, I'm happy to help you through what's involved.

**Comment by heri** [comment]
I can have a look at weather.go

Does it need to use the package `log` or it's also outdated? `log` is not in shared/

**Comment by egtann** [comment]
You won't need that anymore. Just use `p.Log`

**Comment by heri** [comment]
Is there a working plugin where `FollowUp` is different from `Run`?

Made it work for a first Yelp search but not for additional queries. With the updated signature `func FollowUp(in *dt.Msg) (string, error)` seems it doesn't access to the previous response anymore

thanks

**Comment by egtann** [comment]
I'd have to take a look at your code. You shouldn't ever need access to a previous response.  Is it available on Github?

**Comment by heri** [comment]
I haven't pushed any code yet since it doesn't really work yet. @egtann I just sent you an email about mentorship and also a link to a Gist?
